{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "demo2.serviceAccountName" . }}
  labels:
{{ include "demo2.labels" . | indent 4 }}
{{- end -}}
