apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo2.fullname" . }}
  labels:
{{ include "demo2.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
      nodePort: 30001
  selector:
    app.kubernetes.io/name: {{ include "demo2.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

